### ISSUE TITLE
Dose 용량 단위  mg, ug, ng 으로 입력하게 만들기

### ISSUE THREAD

**Issue by shanmdphd** [pipetcpt/dallphin#7]
Dose 용량 단위를 dropdown menu를 만들어 mg, ug, ng 으로 입력하게 만들어야 합니다.

@dlaqudgml2 - `input$dose_unit` 을 만들어 주실 수 있을까요?
@shanmdphd - R 코드에서 각각을 반영할 것.

감사합니다.

**Comment by shanmdphd** [comment]
9fbd9a3ab8520d1d3591160414fa71f368a5c689

**Comment by oceanofscience** [comment]
수고했습니다. 그림 legend에서 VPC의 결과이므로 CI가 아니고 PI (prediction interval)이 아닌가요? PI란 약어는 안쓰이니, 그냥 "5 & 95%iles" 라 쓰든지??

**Comment by shanmdphd** [comment]
@oceanofscience 교수님, 제안 감사합니다. b052df6e3f1367712ebb438108654147ce98eaff 에서 "5 & 95%iles"으로 수정하였습니다. R 코드 관련해서 제안사항 있으시면 언제든 말씀해 주십시오.

![image](https://user-images.githubusercontent.com/6946821/56491880-f24ef680-6524-11e9-8c6b-6eeba9a1bb98.png)
